name = "BayesianAgents"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Guy"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.9"
Distributions = "0.25"
StatsBase = "0.34"
DataStructures = "0.18"
JSON = "0.21, 1"
PyCall = "1.96"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
